const data = {
  products: [
    {
      _id: "1",
      name: "Nha gia kim",
      publishedDate: "10-2013",
      image: "/images/nha-gia-kim.jpeg",
      price: 120,
      oldPrice: 130,
      countInStock: 10,
      author: "Paulo Coelho",
      publisher: "Nhà Xuất Bản Văn Học",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Can bang cam xuc ca luc bao giong",
      author: "Richard Nicholls",
      category: "Shirts",
      image: "/images/can-bang-cam-xuc-ca-luc-bao-giong.jpeg",
      price: 100,
      oldPrice: 130,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Tu dien tieng em",
      author: "Khotudien",
      category: "Khotudien",
      image: "/images/tu-dien-tieng-em.jpeg",
      price: 220,
      oldPrice: 230,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Dan ong sao hoa dan ba sao kim",
      author: "John Gray",
      category: "Pants",
      image: "/images/dan-ong-sao-hoa-dan-ba-sao-kim.jpeg",
      price: 78,
      oldPrice: 130,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Thay doi cuoc song voi nhan so hoc",
      author: "David A. Phillips",
      category: "Pants",
      image: "/images/thay-doi-cuoc-song-voi-nhan-so-hoc.jpeg",
      price: 65,
      oldPrice: 130,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Cay cam ngot cua toi",
      author: "José Mauro de Vasconcelos",
      category: "Pants",
      image: "/images/cay-cam-ngot-cua-toi.jpeg",
      price: 139,
      oldPrice: 190,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
